project:
  type: website  # ここを website にする

# ここでWebサイト上に表示されるタイトルとナビゲーションバー(コンテンツ)を設定
website:
  title: "Tako Data Science Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd  # ここに分析ページへのリンクを追加
        text: Analyses
      - href: demo.qmd  # ここに学習用分析ページへのリンクを追加
        text: Deno Analyses
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
execute:
  cache: true
  freeze: auto  # re-render only when source changes